# Chapter 7

# Working with Missing Data

In [2]:
import pandas as pd
import numpy as np

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

## Filter Out Missing Data

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Those were new objects, to drop within an object, pass axis.

In [18]:
data[4] = np.nan

In [19]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

bad choice for example, it created a 4th column of all nulls then dropped

In [20]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [21]:
df.iloc[:4, 1] = np.nan

In [22]:
df.iloc[:2, 2] = np.nan

In [23]:
df

0         1         2
0 -0.704829       NaN       NaN
1 -0.869488       NaN       NaN
2 -1.012902       NaN  0.793551
3 -0.911104       NaN -0.710205
4 -0.037348 -1.505042 -0.480043
5 -0.225778 -0.720147  0.477771
6 -0.065548  1.448754  2.107412

In [24]:
df.dropna()

0         1         2
4 -0.037348 -1.505042 -0.480043
5 -0.225778 -0.720147  0.477771
6 -0.065548  1.448754  2.107412

In [25]:
df.dropna(thresh=2)

0         1         2
2 -1.012902       NaN  0.793551
3 -0.911104       NaN -0.710205
4 -0.037348 -1.505042 -0.480043
5 -0.225778 -0.720147  0.477771
6 -0.065548  1.448754  2.107412

## Filling In Missing Data

In [26]:
df.fillna(0)

0         1         2
0 -0.704829  0.000000  0.000000
1 -0.869488  0.000000  0.000000
2 -1.012902  0.000000  0.793551
3 -0.911104  0.000000 -0.710205
4 -0.037348 -1.505042 -0.480043
5 -0.225778 -0.720147  0.477771
6 -0.065548  1.448754  2.107412

In [27]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.704829  0.500000  0.000000
1 -0.869488  0.500000  0.000000
2 -1.012902  0.500000  0.793551
3 -0.911104  0.500000 -0.710205
4 -0.037348 -1.505042 -0.480043
5 -0.225778 -0.720147  0.477771
6 -0.065548  1.448754  2.107412

In [3]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [4]:
df.iloc[2:, 1] = np.nan

In [5]:
df.iloc[4:, 2] = np.nan

In [6]:
df

0         1         2
0  0.455492  1.862006 -1.377001
1  1.744132 -0.142659  0.654927
2  0.655032       NaN  1.298510
3  0.661883       NaN -0.257437
4 -1.297187       NaN       NaN
5  0.709536       NaN       NaN

In [7]:
df.fillna(method="ffill")

/var/folders/1b/ykvrss2j11x83bff14t1qwyh0000gp/T/ipykernel_88420/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.455492  1.862006 -1.377001
1  1.744132 -0.142659  0.654927
2  0.655032 -0.142659  1.298510
3  0.661883 -0.142659 -0.257437
4 -1.297187 -0.142659 -0.257437
5  0.709536 -0.142659 -0.257437

## 7.2 Data Transfromation

In [8]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})

In [9]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [10]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [11]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [12]:
data["v1"] = range(7)

In [13]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [16]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [17]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [18]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"], "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [19]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [20]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [21]:
data["animal"] = data["food"].map(meat_to_animal)

In [22]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [24]:
def get_animal(x):
    return meat_to_animal[x]

In [26]:
get_animal("bacon")

'pig'

In [27]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [28]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [29]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [30]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [32]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [33]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [34]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index = ["Ohio", "Colorado", "New York"], columns = ["one", "two", "three", "four"])

In [36]:
def transform(x):
    return x[:4].upper()

In [37]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [38]:
data.index = data.index.map(transform)

In [39]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [40]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [41]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [42]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [43]:
bins = [18, 25, 35, 60, 100]

In [44]:
age_categories = pd.cut(ages, bins)

In [45]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [46]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [47]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [48]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [49]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [50]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [51]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [52]:
data = np.random.uniform(size=20)

In [53]:
pd.cut(data, 4, precision=2)

[(0.24, 0.46], (0.68, 0.89], (0.46, 0.68], (0.24, 0.46], (0.24, 0.46], ..., (0.46, 0.68], (0.021, 0.24], (0.68, 0.89], (0.24, 0.46], (0.24, 0.46]]
Length: 20
Categories (4, interval[float64, right]): [(0.021, 0.24] < (0.24, 0.46] < (0.46, 0.68] < (0.68, 0.89]]

In [54]:
data = np.random.standard_normal(1000)

In [55]:
quartiles = pd.qcut(data, 4, precision=2)

In [56]:
quartiles

[(0.0037, 0.7], (0.7, 3.25], (0.7, 3.25], (-2.8699999999999997, -0.65], (-0.65, 0.0037], ..., (0.7, 3.25], (-2.8699999999999997, -0.65], (-0.65, 0.0037], (0.7, 3.25], (0.0037, 0.7]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.8699999999999997, -0.65] < (-0.65, 0.0037] < (0.0037, 0.7] < (0.7, 3.25]]

In [57]:
pd.value_counts(quartiles)

/var/folders/1b/ykvrss2j11x83bff14t1qwyh0000gp/T/ipykernel_88420/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.8699999999999997, -0.65]    250
(-0.65, 0.0037]                 250
(0.0037, 0.7]                   250
(0.7, 3.25]                     250
Name: count, dtype: int64

### Detecting and Filtering Outliers

In [58]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [59]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000001    -0.008500     0.009372    -0.028922
std       1.005130     1.016985     0.998258     0.994569
min      -3.177289    -3.514261    -3.327650    -2.980422
25%      -0.653440    -0.664538    -0.669627    -0.638592
50%       0.025337    -0.040150     0.001439    -0.031673
75%       0.701347     0.661253     0.689523     0.639635
max       2.960694     3.054815     2.750346     3.082568

In [60]:
col = data[2]

In [61]:
col[col.abs() > 3]

225   -3.227185
495   -3.122072
741   -3.327650
Name: 2, dtype: float64

In [62]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
164  2.446577  0.421054 -1.898459  3.082568
225 -0.016787  0.258601 -3.227185  0.498006
239 -3.113194 -0.473112 -1.301758  0.022642
448  0.262267  3.054815  0.710451 -0.938948
495  0.666927 -0.165912 -3.122072  0.437473
620 -3.177289  1.342786  1.358685 -0.596930
697 -0.373448 -3.514261  1.898871  0.949281
710  0.246217 -3.494287  1.291326 -0.796545
741 -0.136540  0.696574 -3.327650  0.395217
765  1.775351 -3.463172 -1.120232 -1.819421
812 -3.020135 -1.878339  1.047581  0.287814

In [63]:
data[data.abs() > 3] = np.sign(data) * 3

In [64]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.000310    -0.007083     0.010049    -0.029005
std       1.004179     1.012119     0.996126     0.994314
min      -3.000000    -3.000000    -3.000000    -2.980422
25%      -0.653440    -0.664538    -0.669627    -0.638592
50%       0.025337    -0.040150     0.001439    -0.031673
75%       0.701347     0.661253     0.689523     0.639635
max       2.960694     3.000000     2.750346     3.000000

In [65]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0  1.0

### Permutation and Random Sampling

In [66]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [67]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [69]:
sampler = np.random.permutation(5)

In [70]:
sampler

array([1, 4, 3, 0, 2])

In [71]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [72]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [74]:
column_sampler = np.random.permutation(7)

In [75]:
column_sampler

array([0, 2, 5, 4, 6, 3, 1])

In [76]:
df.take(column_sampler, axis="columns")

0   2   5   4   6   3   1
0   0   2   5   4   6   3   1
1   7   9  12  11  13  10   8
2  14  16  19  18  20  17  15
3  21  23  26  25  27  24  22
4  28  30  33  32  34  31  29

In [77]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [78]:
choices = pd.Series([5, 7, -1, 6, 4])

In [79]:
choices.sample(n=10, replace=True)

3    6
2   -1
1    7
3    6
4    4
2   -1
2   -1
1    7
2   -1
4    4
dtype: int64

In [83]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [84]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [85]:
pd.get_dummies(df["key"], dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [86]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)

In [87]:
df_with_dummy = df[["data1"]].join(dummies)

In [88]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [89]:
mnames = ["movie_id", "title", "genres"]

In [90]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::", header=None, names=mnames, engine="python")

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/movielens/movies.dat'

In [91]:
np.random.seed(12345) # to make the example repeatable

In [93]:
values = np.random.uniform(size=10)

In [94]:
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [95]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [96]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False        True       False
1       False       False       False       False        True
2        True       False       False       False       False
3        True       False       False       False       False
4       False        True       False       False       False
5       False       False       False        True       False
6       False       False       False       False        True
7       False       False       False       False        True
8       False       False       False       False        True
9       False       False       False        True       False

In [97]:
s = pd.Series([1, 2, 3, None])

In [98]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [99]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [100]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [101]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [102]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [103]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [104]:
df = pd.DataFrame({"A": [1, 2, None, 4], "B": ["one", "two", "three", None], "C": [False, None, False, True]})

In [105]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [106]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")

In [107]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## String Manipulation

In [109]:
val = "a,b,  guido"

val.split(",")

['a', 'b', '  guido']

In [110]:
pieces = [x.strip() for x in val.split(",")]

In [111]:
pieces

['a', 'b', 'guido']

In [112]:
"::".join(pieces)

'a::b::guido'

In [113]:
"guido" in val

True

In [114]:
val.index(",")

1

In [115]:
val.replace(",", "")

'ab  guido'

### Reg Exp

In [116]:
import re

In [117]:
text = "foo    bar\t baz    \tqux"

In [118]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [119]:
regex = re.compile(r"\s+")

In [120]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [121]:
regex.findall(text)

['    ', '\t ', '    \t']

In [122]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [123]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [124]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [125]:
m = regex.search(text)

In [126]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [127]:
text[m.start():m.end()]

'dave@google.com'

In [128]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [129]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [130]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [131]:
m = regex.match("wesm@bright.net")

In [132]:
m.groups()

('wesm', 'bright', 'net')

In [133]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [134]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


### String Functions Pandas

In [136]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}

In [137]:
data = pd.Series(data)

In [138]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [139]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [140]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [141]:
data_as_string_ext = data.astype('string')

In [142]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [143]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [144]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [145]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [146]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [147]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [148]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [149]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

### Categorical Data

In [150]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [151]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [152]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [153]:
pd.value_counts(values)

/var/folders/1b/ykvrss2j11x83bff14t1qwyh0000gp/T/ipykernel_88420/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [154]:
values = pd.Series([0, 1, 0, 0] * 2)

In [155]:
dim = pd.Series(['apple', 'orange'])

In [156]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [157]:
dim

0     apple
1    orange
dtype: object

In [158]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [159]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2


In [160]:
N = len(fruits)

In [161]:
rng = np.random.default_rng(seed=12345)

In [162]:
df = pd.DataFrame({'fruit': fruits, 'basket_id': np.arange(N), 'count': rng.integers(3, 15, size=N), 'weight': rng.uniform(0, 4, size=N)}, columns=['basket_id', 'fruit', 'count', 'weight'])

In [163]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [164]:
fruit_cat = df['fruit'].astype('category')

In [165]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [166]:
c = fruit_cat.array

In [167]:
type(c)

pandas.core.arrays.categorical.Categorical

In [168]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [169]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [170]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [171]:
df['fruit'] = df['fruit'].astype('category')

In [172]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [173]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [174]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [175]:
categories = ['foo', 'bar', 'baz']

In [176]:
codes = [0, 1, 2, 0, 0, 1]

In [177]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [178]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [179]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [180]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [181]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [182]:
rng = np.random.default_rng(seed=12345)

In [183]:
draws = rng.standard_normal(1000)

In [184]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [185]:
bins = pd.qcut(draws, 4)

In [186]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [187]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [188]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [189]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [190]:
bins = pd.Series(bins, name='quartile')

In [191]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())

/var/folders/1b/ykvrss2j11x83bff14t1qwyh0000gp/T/ipykernel_88420/1488913059.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())


In [192]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [193]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [194]:
N = 10_000_000

In [195]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [196]:
categories = labels.astype('category')

In [197]:
labels.memory_usage(deep=True)

520000132

In [198]:
categories.memory_usage(deep=True)

10000512

In [199]:
%time _ = labels.astype('category')

CPU times: user 255 ms, sys: 36.6 ms, total: 292 ms
Wall time: 303 ms


In [200]:
%timeit labels.value_counts()

185 ms ± 640 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [201]:
%timeit labels.value_counts()

185 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [202]:
%timeit categories.value_counts()

31.3 ms ± 117 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Categorical Methods

In [203]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [204]:
cat_s = s.astype('category')

In [205]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [206]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [207]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [208]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [209]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [210]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [211]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [212]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [213]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [214]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']